#pragma config(Sensor, S1,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



task main()
{


	while(1){

	  //On Track
		while(SensorValue(lightSensor) < 45){
				motor[motorB] = 50;
				motor[motorC] = 50;
		}

		//Off Track
		while(SensorValue(lightSensor) >= 45){

			//250ms
			ClearTimer(time10[T1]);
			while(time10[T1] <= 25){
				//Turn one way
				motor[motorB] = 30;
				motor[motorC] = 0;

				//Checks if it worked
			  if(SensorValue(lightSensor) < 45){
					//Back on track
					break;
				}
			}

			ClearTimer(time10[T1]);
			while(time10[T1] <= 50){
				//Zigzag the other way
				motor[motorB] = 0;
				motor[motorC] = 30;

				//Checks if it worked
				if(SensorValue(lightSensor) < 45){
					//Back on track
					break;
				}
			}

			ClearTimer(time10[T1]);
			while(time10[T1] <= 25){
				//Zigzag back
				motor[motorB] = 30;
				motor[motorC] = 0;
				wait1Msec(250);

				//Checks if it worked
				if(SensorValue(lightSensor) < 45){
					//Back on track
					break;
				}
			}

		}

	}


}
